# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0cd6fd8b7f0443928ad61bb1f11bc139048a8d0574528cb9bf2b2d632482922d2af62fb1bcbbbeaaca1302c8e3413a76cac93dc2d1659a60ced6ade243b2462

test:
  secret_key_base: ffb5bc086e4e4bab484e5b3881d0e08bbe143d8d74225e8f1baece0107d44035fad048ed2009ccabef8c01002c685b25e7cf33355d58f8b911f80263fe5be5b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
